services:
  audiocraft-ub:
    container_name: audiocraft
    build: .
    ports:
      - '7860:7860'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: ["gpu"]
              count: all